CREATE DATABASE IF NOT EXISTS Companydb;

USE Companydb;

CREATE TABLE employee (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) DEFAULT NULL,
    salary INT(5) DEFAULT NULL,
    PRIMARY KEY (ID)
);

DESCRIBE employee;

INSERT INTO employee VALUES
(1,'Joe',1000),
(2,'Henry',2000);
